export type ThemeId = "ai" | "climate" | "health";

export const THEME_LABELS: Record<ThemeId, string> = {
  ai: "AI & SaaS",
  climate: "ClimateTech & Sustainability",
  health: "HealthTech",
};

export type Startup = {
  id: string;
  name: string;
  tagline: string;
  founders: string[];
  hq?: string;
  stage: string;
  funding: string;
  mrr?: string;
  growth?: string;
  customers?: string;
  marketSize?: string;
  burn?: string;
  runway?: string;
  retention?: string;
  strengths: string[];
  risks: string[];
  competitors?: string;
  accelGoal?: string;
  boardScore: number; // 0–10
};

export type ThemeBundle = {
  id: ThemeId;
  label: string;
  startups: Startup[];
  bestIds: string[];
  weakIds: string[];
};

const ai: Startup[] = [
  {
    id: "neuralforge",
    name: "NeuralForge AI",
    tagline: "AI copilots for smart manufacturing plants.",
    founders: ["Arjun Mehta (Ex-Siemens automation lead)", "Kavya Rao (MIT AI researcher)"],
    hq: "Bangalore, India",
    stage: "Seed",
    funding: "$2.5M (Titan Capital, Pioneer Fund)",
    mrr: "$95K",
    growth: "18% MoM",
    customers: "23 enterprise factories",
    burn: "$85K/month",
    runway: "22 months",
    retention: "94%",
    strengths: [
      "Strong enterprise retention",
      "Real operational ROI",
      "Difficult technical moat",
      "High switching costs",
    ],
    risks: ["Long enterprise sales cycles", "Requires implementation support"],
    competitors: "Niche industrial AI vendors; few with proven plant-floor ROI.",
    accelGoal: "Expand to US manufacturing market.",
    boardScore: 9.1,
  },
  {
    id: "echomind",
    name: "EchoMind Labs",
    tagline: "AI emotional wellness companion for Gen Z.",
    founders: ["Co-founders ex-consumer apps"],
    stage: "Seed",
    funding: "$900K",
    mrr: "$22K",
    customers: "1.8M downloads",
    burn: "$120K/month",
    retention: "19%",
    strengths: ["Viral social growth", "Strong branding"],
    risks: ["Weak monetization", "Very poor retention", "No defensible moat"],
    competitors: "Crowded, Replika, Wysa, Youper and dozens more.",
    accelGoal: "Find a sustainable monetization wedge.",
    boardScore: 4.8,
  },
  {
    id: "visionpilot",
    name: "VisionPilot",
    tagline: "Computer vision theft prevention for retailers.",
    founders: ["Retail-tech operators"],
    stage: "Series A",
    funding: "$4M",
    mrr: "$180K",
    customers: "120 retail stores",
    retention: "91%",
    strengths: ["Strong enterprise demand", "Proprietary AI dataset", "Proven ROI"],
    risks: ["Hardware installation dependency"],
    competitors: "Legacy LP vendors; few AI-native players at this accuracy.",
    accelGoal: "Scale across multi-region retail chains.",
    boardScore: 8.8,
  },
  {
    id: "synapseflow",
    name: "SynapseFlow",
    tagline: "AI workflow automation for SMEs.",
    founders: ["Ex-SaaS PMs"],
    stage: "Seed",
    funding: "$1.8M",
    mrr: "$70K",
    customers: "1,400 SMEs",
    strengths: ["Strong SaaS economics", "Easy onboarding"],
    risks: ["Highly crowded category"],
    competitors: "Zapier, Make, n8n and AI-native entrants.",
    accelGoal: "Carve a defensible vertical wedge.",
    boardScore: 7.1,
  },
  {
    id: "medpredict",
    name: "MedPredict AI",
    tagline: "AI diagnostics for hospitals.",
    founders: ["Clinician + ML researcher"],
    stage: "Series A",
    funding: "$6M",
    mrr: "$210K",
    customers: "48 hospital partnerships",
    strengths: ["Healthcare moat", "Strong AI accuracy", "Large market opportunity"],
    risks: ["Regulatory approvals pending"],
    competitors: "Aidoc, Tempus; differentiated by accuracy benchmarks.",
    accelGoal: "Accelerate clinical approvals.",
    boardScore: 8.9,
  },
  {
    id: "scriptly",
    name: "Scriptly AI",
    tagline: "AI content generation for marketers.",
    founders: ["Solo founder"],
    stage: "Pre-seed",
    funding: "$700K",
    mrr: "$30K",
    customers: "14,000 users",
    strengths: ["Fast acquisition", "Easy-to-use product"],
    risks: ["Weak retention", "Highly saturated market", "No differentiation"],
    competitors: "Jasper, Copy.ai, Writesonic and 100+ others.",
    accelGoal: "Find a retention-positive niche.",
    boardScore: 5.4,
  },
  {
    id: "atlasmind",
    name: "AtlasMind Robotics",
    tagline: "AI warehouse robotics optimization.",
    founders: ["Robotics PhDs"],
    stage: "Series A",
    funding: "$8M",
    mrr: "$250K",
    burn: "$340K/month",
    strengths: ["DeepTech moat", "Large automation market"],
    risks: ["Very high burn", "Hardware-heavy scaling"],
    competitors: "Locus, GreyOrange; capital-intensive category.",
    accelGoal: "Win marquee 3PL contracts.",
    boardScore: 8.2,
  },
  {
    id: "quantedge",
    name: "QuantEdge AI",
    tagline: "AI-powered financial forecasting engine.",
    founders: ["Ex-quant + ML lead"],
    stage: "Seed",
    funding: "$3M",
    mrr: "$120K",
    retention: "96%",
    strengths: ["Sticky enterprise workflows", "Strong retention", "Predictable SaaS revenue"],
    risks: ["Reliance on external APIs"],
    competitors: "In-house quant teams; few SaaS-native players.",
    accelGoal: "Land enterprise CFO-office partnerships.",
    boardScore: 8.7,
  },
];

const climate: Startup[] = [
  {
    id: "carbonloop",
    name: "CarbonLoop",
    tagline: "Industrial carbon capture systems.",
    founders: ["Industrial engineers"],
    stage: "Series A",
    funding: "$9M",
    mrr: "$300K",
    customers: "14 enterprise clients",
    strengths: ["Massive climate opportunity", "Strong industrial demand", "Government incentives"],
    risks: ["Expensive deployments", "Long installation cycles"],
    competitors: "Climeworks, Carbon Clean, capital-heavy field.",
    accelGoal: "Scale into cement & steel verticals.",
    boardScore: 9.0,
  },
  {
    id: "aquagrid",
    name: "AquaGrid",
    tagline: "Smart water optimization for cities.",
    founders: ["GovTech operators"],
    stage: "Seed",
    funding: "$2M",
    mrr: "$75K",
    strengths: ["Government pilot projects", "Real sustainability impact"],
    risks: ["Slow procurement cycles"],
    competitors: "Few AI-native players; mostly legacy utility vendors.",
    accelGoal: "Convert pilots into multi-year contracts.",
    boardScore: 7.4,
  },
  {
    id: "solvix",
    name: "Solvix Energy",
    tagline: "AI-managed solar storage grids.",
    founders: ["Energy + ML founders"],
    stage: "Series A",
    funding: "$6M",
    mrr: "$190K",
    strengths: ["Recurring enterprise contracts", "Strong infrastructure demand"],
    risks: ["Energy market dependence"],
    competitors: "Stem, Fluence; differentiated by AI dispatch.",
    accelGoal: "Expand into commercial storage assets.",
    boardScore: 8.9,
  },
  {
    id: "greenchain",
    name: "GreenChain Logistics",
    tagline: "Carbon-neutral logistics optimization.",
    founders: ["Logistics operators"],
    stage: "Seed",
    funding: "$1.2M",
    mrr: "$40K",
    strengths: ["Sustainability trend alignment"],
    risks: ["Weak differentiation", "Low defensibility"],
    competitors: "Crowded, every TMS now markets carbon features.",
    accelGoal: "Find a defensible wedge.",
    boardScore: 5.5,
  },
  {
    id: "terrafuel",
    name: "TerraFuel",
    tagline: "Biofuel alternatives for aviation.",
    founders: ["Chemical engineers"],
    stage: "Series B",
    funding: "$12M",
    mrr: "$150K",
    strengths: ["Huge market opportunity", "Strategic airline partnerships"],
    risks: ["Extremely capital intensive"],
    competitors: "LanzaJet, Neste; long capex cycles.",
    accelGoal: "Secure offtake agreements with carriers.",
    boardScore: 8.0,
  },
  {
    id: "ecobyte",
    name: "EcoByte",
    tagline: "Climate analytics for enterprises.",
    founders: ["ESG consultants"],
    stage: "Seed",
    funding: "$2.8M",
    mrr: "$110K",
    strengths: ["ESG reporting demand", "SaaS margins"],
    risks: ["Competitive analytics market"],
    competitors: "Watershed, Persefoni and many others.",
    accelGoal: "Differentiate through audit-grade methodology.",
    boardScore: 7.7,
  },
  {
    id: "puresoil",
    name: "PureSoil Labs",
    tagline: "Soil regeneration biotechnology.",
    founders: ["Agri-bio researchers"],
    stage: "Seed",
    funding: "$3.5M",
    strengths: ["Strong sustainability impact"],
    risks: ["Long adoption cycles", "Difficult monetization"],
    competitors: "Indigo, Pivot Bio, long sales cycles.",
    accelGoal: "Find paying anchor customers.",
    boardScore: 5.9,
  },
  {
    id: "windsync",
    name: "WindSync",
    tagline: "Wind turbine optimization platform.",
    founders: ["Energy infra operators"],
    stage: "Series A",
    funding: "$5M",
    mrr: "$160K",
    strengths: ["Infrastructure partnerships", "Strong recurring revenue"],
    risks: ["Requires enterprise-heavy scaling"],
    competitors: "GE Digital, Siemens Gamesa; AI-native edge.",
    accelGoal: "Land global IPP partnerships.",
    boardScore: 8.7,
  },
];

const health: Startup[] = [
  {
    id: "pulsetrack",
    name: "PulseTrack",
    tagline: "Remote cardiac monitoring infrastructure.",
    founders: ["Cardiologist + engineer"],
    stage: "Series A",
    funding: "$5M",
    mrr: "$200K",
    customers: "70 hospital partnerships",
    strengths: ["Strong clinical adoption", "High retention", "Recurring hospital contracts"],
    risks: ["Regulatory approvals required"],
    competitors: "iRhythm, BioTel, differentiated by infra model.",
    accelGoal: "Expand into US hospital networks.",
    boardScore: 9.2,
  },
  {
    id: "geneticore",
    name: "GenetiCore",
    tagline: "AI genomics analysis platform.",
    founders: ["Genomics + ML founders"],
    stage: "Series A",
    funding: "$8M",
    mrr: "$170K",
    strengths: ["Proprietary data moat", "High scientific defensibility"],
    risks: ["Long commercialization timelines"],
    competitors: "Tempus, Illumina ecosystem.",
    accelGoal: "Partner with leading research hospitals.",
    boardScore: 8.4,
  },
  {
    id: "caresync",
    name: "CareSync",
    tagline: "Hospital workflow automation.",
    founders: ["Healthcare ops + SaaS"],
    stage: "Seed",
    funding: "$3M",
    mrr: "$110K",
    strengths: ["Clear operational ROI", "Strong retention"],
    risks: ["Enterprise onboarding complexity"],
    competitors: "Epic-adjacent tools; AI-native edge.",
    accelGoal: "Scale into mid-market hospital chains.",
    boardScore: 8.6,
  },
  {
    id: "vitasense",
    name: "VitaSense",
    tagline: "Wearable health analytics.",
    founders: ["Consumer hardware team"],
    stage: "Seed",
    funding: "$2M",
    mrr: "$55K",
    strengths: ["Strong consumer demand"],
    risks: ["Weak long-term engagement", "High churn"],
    competitors: "Whoop, Oura, Fitbit — brutal category.",
    accelGoal: "Find a B2B2C wedge.",
    boardScore: 5.7,
  },
  {
    id: "medilink",
    name: "MediLink",
    tagline: "Telemedicine SaaS infrastructure.",
    founders: ["Telehealth operators"],
    stage: "Series A",
    funding: "$4M",
    mrr: "$180K",
    strengths: ["Large telehealth market", "Strong recurring revenue"],
    risks: ["Competitive category"],
    competitors: "Amwell, Doxy; differentiated infra.",
    accelGoal: "Win regional health system contracts.",
    boardScore: 7.8,
  },
  {
    id: "biopulse",
    name: "BioPulse AI",
    tagline: "AI-powered drug discovery.",
    founders: ["Computational biology PhDs"],
    stage: "Series A",
    funding: "$10M",
    burn: "$480K/month",
    strengths: ["Massive upside potential", "Strong IP"],
    risks: ["Very long commercialization cycle", "Extremely capital intensive"],
    competitors: "Insitro, Recursion; capital-intensive.",
    accelGoal: "Sign pharma co-development deal.",
    boardScore: 7.5,
  },
  {
    id: "healmate",
    name: "HealMate",
    tagline: "Mental wellness subscription platform.",
    founders: ["Consumer founders"],
    stage: "Pre-seed",
    funding: "$1M",
    mrr: "$25K",
    strengths: ["Growing awareness market"],
    risks: ["Weak monetization", "Poor retention"],
    competitors: "Calm, Headspace, BetterHelp — crowded.",
    accelGoal: "Find a defensible payer wedge.",
    boardScore: 4.6,
  },
  {
    id: "nanocure",
    name: "NanoCure Labs",
    tagline: "Nano-tech cancer diagnostics.",
    founders: ["Bioengineering researchers"],
    stage: "Series A",
    funding: "$7M",
    mrr: "$150K",
    strengths: ["Deep scientific moat", "Strong healthcare partnerships"],
    risks: ["Regulatory complexity"],
    competitors: "Grail, Guardant — differentiated nano platform.",
    accelGoal: "Accelerate FDA pathways.",
    boardScore: 8.9,
  },
];

export const THEMES: Record<ThemeId, ThemeBundle> = {
  ai: {
    id: "ai",
    label: THEME_LABELS.ai,
    startups: ai,
    bestIds: ["neuralforge", "visionpilot", "quantedge"],
    weakIds: ["echomind", "scriptly"],
  },
  climate: {
    id: "climate",
    label: THEME_LABELS.climate,
    startups: climate,
    bestIds: ["carbonloop", "solvix", "windsync"],
    weakIds: ["greenchain", "puresoil"],
  },
  health: {
    id: "health",
    label: THEME_LABELS.health,
    startups: health,
    bestIds: ["pulsetrack", "nanocure", "caresync"],
    weakIds: ["healmate", "vitasense"],
  },
};