/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsBscRouteImport } from './routes/simulations.bsc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsBscRoute = SimulationsBscRouteImport.update({
  id: '/simulations/bsc',
  path: '/simulations/bsc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulations/bsc': typeof SimulationsBscRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulations/bsc': typeof SimulationsBscRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulations/bsc': typeof SimulationsBscRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulations/bsc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulations/bsc'
  id: '__root__' | '/' | '/simulations/bsc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulationsBscRoute: typeof SimulationsBscRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/bsc': {
      id: '/simulations/bsc'
      path: '/simulations/bsc'
      fullPath: '/simulations/bsc'
      preLoaderRoute: typeof SimulationsBscRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulationsBscRoute: SimulationsBscRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
